In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
X = np.arange(1, 21)
Y = 2**X / X

Y

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

In [3]:
Y2 = map(lambda k: 2**k / k, X)
list(Y2)

[2.0,
 2.0,
 2.6666666666666665,
 4.0,
 6.4,
 10.666666666666666,
 18.285714285714285,
 32.0,
 56.888888888888886,
 102.4,
 186.1818181818182,
 341.3333333333333,
 630.1538461538462,
 1170.2857142857142,
 2184.5333333333333,
 4096.0,
 7710.117647058823,
 14563.555555555555,
 27594.105263157893,
 52428.8]

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
## your code
i = np.arange(6)
np.sum(0.1**(3*i) * 0.2**(4*i))

1.00000160000256

In [5]:
sum([0.1**(3*i) * 0.2**(4*i) for i in range(6)])

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
## your code
X = np.zeros((8,8), dtype=int)
X[1::2, ::2] = 1
X[::2, 1::2] = 1

X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [7]:
X = np.random.random((5, 2))

## your code
x1, x2 = X[:, 0], X[:, 1]
# X, x1, x2
ro = np.sqrt(x1**2 + x2**2)
tau = np.arctan2(x2, x1)

ro, tau

(array([0.09334802, 0.24362594, 0.84017074, 1.14864219, 0.25646775]),
 array([0.35092191, 1.09886803, 0.58454617, 0.54218794, 1.29938407]))

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [8]:
X = np.random.random((10, 10))

# your code
index_of_max = np.unravel_index(np.argmax(X), X.shape)
X, index_of_max

# check
np.max(X) == X[index_of_max[0], index_of_max[1]]

True

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [9]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
dist = ((X - y)[:, 0]**2 + (X - y)[:, 1]**2)
closest_index = np.argmin(dist)

# check
(sp.spatial.distance.cdist(X, y)).argmin() == closest_index

True

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [10]:
## your code
split1 = np.arange(-3, 0, 0.5)
split2 = np.arange(0, 2, 0.5)
split3 = np.linspace(2, 3, 3)

f1 = lambda x: x**2 + 2*x + 6
f2 = lambda x: x + 6
f3 = lambda x: x**2 + 4*x - 4

var1 = np.concatenate((f1(split1), f2(split2), f3(split3)), axis=None)
var2 = np.hstack((f1(split1), f2(split2), f3(split3)))

print(var1)
print(var2)

[ 9.    7.25  6.    5.25  5.    5.25  6.    6.5   7.    7.5   8.   12.25
 17.  ]
[ 9.    7.25  6.    5.25  5.    5.25  6.    6.5   7.    7.5   8.   12.25
 17.  ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [11]:
X = np.random.random((10, 10))

## your code
Y = X - X.mean(axis=1, keepdims=True)

# check
Y.mean(axis=1, keepdims=True)

array([[-4.99600361e-17],
       [ 3.33066907e-17],
       [ 0.00000000e+00],
       [-1.11022302e-16],
       [ 2.22044605e-17],
       [ 5.55111512e-17],
       [ 4.44089210e-17],
       [ 4.44089210e-17],
       [-8.88178420e-17],
       [ 0.00000000e+00]])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [12]:
X = np.random.normal(loc=5, scale=2., size=1000) 
# loc - это выборочное среднее, scale - выборочное стандартное отклонение
X.mean(), X.var()

(5.004300157045135, 3.931752246531919)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [13]:
## your code
a = np.ones((5, 5)) * np.arange(5)
a += a.T
a %= 5
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [14]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        print(f'val = {val}')
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)

val = 1.0441166998885185
val = 50.564484315853676
val = 48.87692326506126
val = 28.502474769912652
val = 68.07351306629009


[0, 1, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [15]:
def better_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    partial = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    print(f'val = {val}')
    partial -= val.T
    partial[partial >= 0] = 0
    
    return np.argmax(partial, axis=0)

better_sample([50, 3, 1, 7, 20], 5)

val = [15.13155564 27.13256528 47.27818844 43.30421269 16.98124484]


array([0, 0, 0, 0, 0], dtype=int64)